name: EasyLibrary
version: 1.3.0

authors: 
 - ImperaZim
 
api: 5.0.0
main: Library
load: STARTUP

extensions:
  Core: ">=8.2"
  
permissions:
  easylibrary.command.genplugin:
    default: op 
    description: Generate a new plugin base with EasyLibrary