name: PluginExample
version: 1.0.0
api: 5.0.0
main: ImperaZim\PluginExample
author: ImperaZim
depend:
  - EasyLibrary
  
permissions: 
  plugin.permission:
    default: true 
    description: "General permission"